modLoader="javafml"
loaderVersion="[45,)"
license="MIT"
[[mods]]
modId="examplemod"
version="${file.jarVersion}"
displayName="Minecraft Sound Engineers"
description="An example mod for Minecraft 1.21"
authors="Isak Grönlund"
contact="gronlundisak11@gmail.com"
[[dependencies.examplemod]]
modId="forge"
mandatory=true
versionRange="[45,)"
ordering="NONE"
side="BOTH"
